name: linting-checks

on: [push, pull_request]

jobs:
  lint:
    if: github.repository == 'hasktorch/hasktorch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v10
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: |
          .github/workflows/setup-iohk-cache.sh
      - run: |
          cachix use pre-commit-hooks
      - run: |
          nix-shell --command "pre-commit run --all-files --show-diff-on-failure"
