name: nix-linux

on: [push, pull_request]

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v12
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: |
            nix build .#codegen-cpu
            nix build .#hasktorch-cpu
            nix build .#hasktorch-gradually-typed-cpu
            nix build .#libtorch-ffi-cpu
            nix build .#libtorch-ffi-helper-cpu
            nix build .#codegen-gpu
            nix build .#hasktorch-gpu
            nix build .#hasktorch-gradually-typed-gpu
            nix build .#libtorch-ffi-gpu
            nix build .#libtorch-ffi-helper-gpu
