name: stack-macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - name: Setup tool-chains
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install libomp || true
        pip3 install pyyaml || true
        #wget -qO- https://get.haskellstack.org/ | sed -e 's/^STACK_VERSION=.*/STACK_VERSION="1.9.3"/g' | sh || true
        wget -qO- https://get.haskellstack.org/ | sh || true
        clang --version
        stack --version
        brew tap hasktorch/libtorch-prebuild https://github.com/hasktorch/homebrew-libtorch-prebuild || true
        brew install libtorch-prebuild@1.7 || true
        #pushd deps/ ; ./get-deps.sh -a cpu -c ;popd
    - name: Build
      run: |
        #. setenv
        stack build --stack-yaml stack-ghc88.yaml
    - name: Test
      run: |
        #. setenv
        stack test codegen  --stack-yaml stack-ghc88.yaml
        stack test libtorch-ffi  --stack-yaml stack-ghc88.yaml
        stack test hasktorch --stack-yaml stack-ghc88.yaml
        stack exec codegen-exe --stack-yaml stack-ghc88.yaml
        stack exec xor-mlp --stack-yaml stack-ghc88.yaml
        stack exec regression --stack-yaml stack-ghc88.yaml
        stack exec gaussian-process --stack-yaml stack-ghc88.yaml
        stack exec vae --stack-yaml stack-ghc88.yaml
        stack exec optimizers --stack-yaml stack-ghc88.yaml
